### ISSUE TITLE
Idea: For platform stacks that use nginx, move nginx conf into /opt/app/

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#116]
Purpose of this issue:

- Propose an idea, and ask @zarvox and others if it is a good idea, and request other better ideas in the process.

Plan:

- I hope people discuss this idea here, at least saying +1 or -1, and preferably suggesting other ideas or specific criticisms.

- If there seems to be consensus for it, then I'll write, "Seems like we all think it's a good idea. Great!", and then I'll close this, and then I'll file a bug actually requesting the change. If there isn't consensus for it, or there is indeed consensus it's a bad idea, then I will close this.

- My timeline is I'd like to decide yes/no on this by next Friday (Fri Jan 29). No massive urgency and I can accept some delay; just leave a comment requesting it.

Status quo:

- `setup.sh` mutates a global set of nginx configuration files.
- This means that when one wants to modify the nginx configuration, one must `cd .sandstorm ; vagrant provision ; cd ..`
- Additionally @nicosomb just ran into a problem where he was using `$1` as part of the nginx configuration (to mirror https://www.nginx.com/resources/wiki/start/topics/recipes/symfony/ ) and ran into a problem: `==> default: /opt/app/.sandstorm/setup.sh: line 9: $1: unbound variable` ; I _think_ bash heredocs support variable expansion, which neither he nor I expected in this case.

Proposal:

- For the platform stacks where we use nginx (`lemp` `uwsgi` `static`) (but using the filenames from `lemp` as an example), adjust `setup.sh` to not create `/etc/nginx/sites-available/sandstorm-php` going forward
- Make `/etc/nginx/sites-available/sandstorm-app` be a symlink to `/opt/sandstorm/.sandstorm/nginx.conf`

Backwards compatibility:

- I believe there's no backwards compatibility impact on existing vagrant-spk packages; they can enjoy their current situation.
- If they ever decide to refresh their `.sandstorm/*.sh` via `vagrant-spk setupvm lemp`, then they already expect to lose any customizations they've made to nginx.conf.
- For backwards compatibility clarity, in `setup.sh`, before we make a symlink to `/opt/app/.sandstorm/nginx.conf` we should check if the old filename (`/etc/nginx/sites-available/sandstorm-php`) exists on the filesystem. If it does, we should abort and tell the user they should either `rm` the old filename, or `vagrant destroy` then `vagrant up`.

**Comment by zarvox** [comment]
I'd like to propose an even more-aggressive option which I think has even more to like:

* For platform stacks where we use nginx, adjust `setup.sh` to not create `/etc/nginx/sites-available/sandstorm-$STACK` or modify any of the distro-provided nginx config.
* Add a hook in `vagrant-spk` to allow stacks to provide additional files/folders that should be copied into `$PROJECT_ROOT/.sandstorm` directly.
* Provide an *entire* flattened nginx conf as part of the stacks using the hook added above.
* Adjust the `launcher.sh` scripts to launch `nginx` with an explicit `-c /opt/app/.sandstorm/nginx.conf`.

Backwards-compatibility:
* No breakage, including on subsequent `vagrant-spk setupvm $STACK` invocations

Benefits:
* We no longer need a bunch of fancy logic in `setup.sh` that needs to be updated when Debian changes their default-shipped config files
* Debian config changes cannot break the package
* Packagers can more easily modify the nginx config, since it's now just a file in their repo, rather than "the sum of what Debian packages + these changes made by imperative bash scripts and sed"

Drawbacks:
* App packagers might have to include a decent chunk of boilerplate in their `.sandstorm/nginx.conf`.  But since `vagrant-spk` is providing the baseline, they don't have to write it from scratch.
* app-vendored nginx configs may not get updated if authors aren't paying attention

Other thoughts:
* Depending on complexity and platform-specificness, it might even be worth following this approach for shrinkwrapping configs for other dependencies, such as php5-fpm, uwsgi, or mysql.

**Comment by paulproteus** [comment]
I basically love this. I'd like to suggest some further bit of bikeshedding which is:

- Create a `.sandstorm/service-config/` directory, and put `nginx.conf` and `mysql.conf` etc. in there. That way, it's a little tidier.

I'm +1 on your current proposal, even without the directory thing.

**Comment by zarvox** [comment]
Sure, +1 on your amendment.

I'm generally cautious about introducing a bunch of unnecessary hierarchy, especially if there's only going to be one or two files in that folder, but this seems reasonable.

**Comment by paulproteus** [comment]
FWIW, if we end up at the point where `vagrant-spk` is not mutating global state at _all_, then we end up in a situation where something like `lxc` as an alternate backend works A-OK, and where therefore Travis-CI etc. are easy to support.
