### ISSUE TITLE
Retire meteor-spk/existing Meteor stack

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/vagrant-spk#153]
1. The existing setup conflicts with current documentation for Sandstorm development and behaves in surprising ways.
2. Every other stack emits comprehensible shell scripts, and it's easy to tweak them for specific needs.
3. Meteor is about to rapidly evolve. There are proposals for [upgrading node.js](https://github.com/meteor/meteor/issues/5124), [a new proposed stack for moving Meteor to GraphQL and separating out reactivity](https://github.com/apollostack) and, most exciting for Sandstorm, a [sample todos app based on this stack that uses SQLite](https://github.com/apollostack/todos).

IOW, if Sandstorm will be shipping its own versions of Node/Mongo and putting everything into a sandbox, then you'll be making lots of extra work for yourselves. Further, you'll be excluding app developers who want to use Meteor but not Mongo (I.e. me, as soon as I can reliably jump ship to a better database. :) You'll also be making it harder for app developers who want to integrate Meteor's reactivity into processes that might be better driven by external binaries, or just about anything outside of the Meteor/Node ecosystem.

One possible path forward might be the work I did [here](https://github.com/ndarilek/alexandria/tree/master/.sandstorm). I think the only extra addition it might need is an `--always-include` flag to `spk`, because I include /home/vagrant/bundle in the compiled app and I don't think there's a way to do that otherwise.

This setup should be backwards-compatible with existing apps but I can't say for sure. It installs node 0.10.x so should work with older Meteor versions, but symlinks Meteor's shipped node version in for 1.3+ which supports `meteor node`. It downloads the community Mongo packages so should work with stock Meteor. And it's easy to drop the Mongo dependency if you want Rethink or SQLite or something we haven't even thought of yet. I don't think the spks it ships are significantly larger than those from meteor-spk.

**Comment by kentonv** [comment]
The thing is, `meteor-spk` is incredibly easy to use for anyone who fits the "usual pattern" of a Meteor/Mongo project. It avoids the whole tracing step, which is great because the tracing step is error-prone, especially if you do most of your testing and development outside of Sandstorm, which Meteor users probably do.

Maybe it makes sense to introduce an alternative for Meteor projects that have non-typical dependencies, but I don't think meteor-spk should be retired unless the alternative is just as easy to get set up.

**Comment by ndarilek** [comment]
That's fair. An alternative take is that there's a huge body of good 
documentation and support for developing apps in Sandstorm, and your 
"usual" developer is going to have to learn some of that anyway. It will 
be a bit odd if they read up on a bunch of aspects of Sandstorm 
development only to realize that much of that doesn't apply to the 
Meteor stack.

As far as tracing, if I bundle the Meteor app under /home/vagrant/bundle 
and --always-include that, doesn't the tracer pretty much get removed 
from the picture? Maybe it misses some external dependencies, but it 
seems like if you're using any of those then you're already beyond what 
your usual Meteor developer would expect from the old Meteor stack and 
know what you need to do. You're also beyond what meteor-spk would allow.

I also think the concept of the Meteor "usual" developer is going to 
start changing rapidly soon. We're already almost at Meteor 1.3.2, and 
word on the street is there's already a Meteor app building with Node 
5.X with PRs to upgrade Meteor following shortly. I think there will 
always be a `meteor new app && cd app && meteor` track, but that will 
just be the starting point. I personally can't remember the last time I 
ran `meteor new` and didn't immediately do a whole bunch of stuff to 
replace the view layer with React, the languages used, etc. and as soon 
as I can do that with Mongo you'd better believe I'm switching to 
Rethink or Postgres. :)

If we don't retire it, could we perhaps make the plain "meteor" stack 
the new version, with "meteor-spk" for those who want to stick with more 
traditional Meteor development? I know you all put a lot of work into 
crafting an easier Meteor development experience, and thank you for 
that, but I'm worried that we're used to a Meteor that doesn't change 
for months at a stretch (at least since 1.0) and now we're getting point 
releases every week, with a pretty impressive roadmap. I want to be able 
to use all of that new functionality in Sandstorm apps, and call it the 
"meteor" stack when I do. :)

**Comment by kentonv** [comment]
You'll need the tracing to discover your node binary, your database binary, and their respective dependencies, which Meteor does not automagically include in its build output. That's what meteor-spk avoids: it bundles a known-good copy of node and mongo and all their dependencies so you don't need to trace for them.

Keep in mind that meteor-spk does not stop you from using most new features in Meteor. There is absolutely nothing stopping you from using e.g. React with meteor-spk. The only thing that really matters is databases (or other external daemons), since Meteor's build doesn't bundle those automatically.

Also note that meteor-spk does *not* need to be updated for every Meteor release. It really only needs to be bumped when the underlying Node version changes, which doesn't happen weekly. It's not very hard for me to push a new meteor-spk release whenever there's a node bump -- yes, even when it's going from 0.10.x -> 4.x, it should be no big deal.

When Meteor starts supporting multiple databases, then I think the right path forward for meteor-spk is to tell everyone to use sqlite. Sqlite is almost always the database you want to be using on Sandstorm -- others (including Mongo) are optimized for a very different use case. I suspect Meteor's use of sqlite will not require a separate daemon, so nothing new will need to be added to the meteor-spk bundle. We may want to adjust the startup scripts to avoid starting Mongo if it isn't needed, but that's about it.

So yeah, I'm honestly not seeing a lot of friction in the future for meteor-spk.

**Comment by paulproteus** [comment]
FWIW, if "platform stacks" supported the idea of customizing the
.sandstorm/sandstorm-pkgdef.capnp with details specific to the stack, then
'meteor-spk' could act more "normal" in terms of still supporting the FUSE
hack for adding other filesystem paths. The fact that it doesn't has been a
problem for at least two Sandstorm apps, as I recall, one of which I recall
specifically.

**Comment by ocdtrekkie** [comment]
I think I am going to close this one.

- I think having multiple development tools (now docker-spk, and someday nix-spk) is valuable for different workflows and preferences.
- The vagrant-spk tool's position as a basic/core option means it should opt to provide experiences for most stacks, including Meteor.
- meteor-spk is used by vagrant-spk so must also be maintained anyways, and is useful on it's own, actively for some apps maintained today.
