### ISSUE TITLE
Crashes on Python 2.5 due to use of "with"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#17]
https://www.evernote.com/shard/s59/sh/58db80b4-e6b6-44e6-98f5-856b5b05e428/50ac01dc4ea0fe8f/deep/0/

The key here is that `with` didn't exist in Python 2.5.

**Comment by paulproteus** [comment]
@zarvox sorry for the push without a pull request; it'd be nice to get your +1 on https://github.com/sandstorm-io/vagrant-spk/commit/6603626da244ca3c3747044f24be41d54d8eebd7 at some point.

(Trying to debug things for @jadeqwang and figured it was best to solve the issue in mainline `vagrant-spk` rather than having her use a fork.)

**Comment by zarvox** [comment]
Yeah, that's pretty sad.

It's been a long time since I had to support Python older than 2.7; even Cygwin Python is up to 2.7 these days.  Debian oldstable has Python 2.7.3.  Squeeze had 2.6.6.  Even RHEL 6 has Python 2.6.

Anyone on a recent OSX version is going to have 2.7 installed and on $PATH by default.  I think maybe it'd be worthwhile to have some instructions on how to get an up-to-date Python longer-term - I forget when subprocess was added, and which options to subprocess were 2.6 vs 2.7.

So I guess I'm saying while this is fine for now, it'd be nice to be able to assume 2.7, and dictionary comprehensions, since pretty much all the developer machines I can think of *can* safely use 2.7, and the vast majority will have it by default.

Perhaps we can document getting an up-to-date Python?

**Comment by paulproteus** [comment]
I would be pretty radically sad if we ended up asking people to install a
newer Python intepreter in addition to all the other stuff we ask them to
install. There is untold quadratic sadness explosion for users of
vagrant-spk if we go that route, and I have seen so much of it in my years
of intro Python workshop teaching.

**Comment by zarvox** [comment]
I think my point was that the vast, vast majority of developers are on systems with sufficiently modern Python, and will be able to skip that step.

An alternate approach is building bundles for all OSes, and packaging that and distributing that, Python runtime and all.  Which is probably what we'll do for Windows anyway.

**Comment by zarvox** [comment]
Oh, another thing I noticed that won't work in Python 2.5:

```python
"{}".format('hi')
```
must be rewritten as
```python
"{0}".format('hi')
```
in Python 2.6.

In Python 2.5, the situation is even worse: `str.format` doesn't exist at all; you're stuck using the % operator for string substitution.

Python 2.5 is now almost 10 years old.  My impression is that this is not unlike asking for IE6 support or Windows Vista support.  Can we make the #! be for `/usr/bin/python2.7` instead or something, which might save us on weirdly-configured OSX machines?

(Considering that Python 3 is the future, I'd like for the code to be Python3k-clean, which is also nigh-impossible when supporting 2.5)
