### ISSUE TITLE
packaging-tutorial composer fail

### ISSUE THREAD

**Issue by n-a-m-e** [sandstorm-io/vagrant-spk#186]
attempting https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial/

running

`vagrant-spk dev`

failed because composer said php mcrypt, gmp and gd were missing

fix was:
```
vagrant-spk ssh

sudo apt-get install php5-mcrypt php5-gmp php5-gd
```

Then exit the SSH session with CTRL+D
and try again:

`vagrant-spk dev`

**Comment by paulproteus** [comment]
Hi @n-a-m-e ,

Do you get this error using the specific app we use in the tutorial?

Or is it specific to an app you're trying to package, rather than our example app?

If it's specific to your own app, then:

- Please accept my apologies that the documentation doesn't make it clear what exactly you should modify.

- Additionally, per https://docs.sandstorm.io/en/latest/vagrant-spk/customizing/#setupsh , `.sandstorm/setup.sh` is a good place to leave those `apt` commands.

Let me know!

**Comment by n-a-m-e** [comment]
Yeah I just figured out that it's to do with a specific app. I'm trying to package https://www.invoiceninja.com/ which has an indepth tutorial on how to set it up with nginx and debian here https://www.rosehosting.com/blog/install-invoice-ninja-on-a-debian-7-vps/ thanks for the hint about `.sandstorm/setup.sh` thanks for the quick reply.

**Comment by paulproteus** [comment]
You're very welcome! I'm glad I'm able to help.

**Comment by paulproteus** [comment]
For now I'll close this issue; @n-a-m-e please feel free to ask me for help, either here, or on the issue tracker for your Sandstorm app!
