### ISSUE TITLE
Error when using VirtualBox 5.2 and Vagrant 2.1.2

### ISSUE THREAD

**Issue by urakagi** [sandstorm-io/vagrant-spk#237]
I installed VirtualBox 5.2 on a Windows machine and run `vagrant-spk`, then `Vagrant` says 5.2 is not supported. So I update `Vagrant` to 2.1.2, then `vagrant-spk vm up` throws error:
```
C:\Users\Romulus\WebstormProjects\sandmd>vagrant-spk vm up
Calling 'vagrant' 'up' in C:\Users\Romulus\WebstormProjects\sandmd\.sandstorm
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/Users/Romulus/WebstormProjects/sandmd/.sandstorm/Vagrantfile
Line number: 13
Message: RuntimeError: can't modify frozen String
[31mCommand failed with a non-zero exit status (1).[0m
```

That line seems to be a hack, so I remove it. Then the error becomes:
```
C:\Users\Romulus\WebstormProjects\sandmd>vagrant-spk vm up
Calling 'vagrant' 'up' in C:\Users\Romulus\WebstormProjects\sandmd\.sandstorm
Bringing machine 'default' up with 'virtualbox' provider...
The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: 2

  Minimum required version: 3
[31mCommand failed with a non-zero exit status (1).[0m
```

I can't find where to update Powershell, but it seems like `vagrant-spk` needs an update?

**Comment by ocdtrekkie** [comment]
@kentonv hasn't pushed a Windows release with the fix for the first issue. Removing it is an adequate fix, I did this: https://github.com/sandstorm-io/vagrant-spk/commit/e0c1d4c086ad207af53f7b7f49ec6f656aec4b8d

Your PowerShell issue seems to be an issue with the version of Windows you are on, and how Vagrant feels about it. You can either upgrade your PowerShell version or downgrade Vagrant to 1.9.6. Here's where you can find the WMF download for your version of Windows: https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-windows-powershell?view=powershell-6

**Comment by urakagi** [comment]
@ocdtrekkie Thank you, I updated PowerShell to 5.0 and the error is fixed.
