### ISSUE TITLE
Disable gzip by default in nginx

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/vagrant-spk#33]
### Steps to reproduce

If you create a new VM with `vagrant-spk` with the `lemp` backend, and it happens to be the case that the directory you point nginx to has no `index.php`, then nginx wants to give you a `403 Forbidden` page.

### Actual results

With the current setup, what I see is the following gibberish:

```
ï¿½í±!ï¿½wß¡ï¿½ï¿½ï¿½ï¿½qBï¿½ï¿½ï¿½ï¿½Oï¿½zï¿½p`ï¿½Dï¿½ï¿½=ï¿½ï¿½ï¿½Ø¿_ï¿½6&ï¿½NN'ÂB)ï¿½Mï¿½ï¿½jï¿½ï¿½}ï¿½ï¿½"ï¿½ï¿½
ï¿½D2ï¿½ï¿½ï¿½6ï¿½7ï¿½ï¿½ï¿½DUQï¿½ï¿½E)Lï¿½mÈ‰ï¿½cï¿½ï¿½ï¿½ï¿½Xï¿½ï¿½ï¿½;oï¿½uï¿½ï¿½$xï¿½Qï¿½ï¿½}ßŒ1PpQï¿½ï¿½wï¿½ï¿½ï¿½*ï¿½ï¿½ï¿½ï¿½ï¿½GØšzï¿½sï¿½ï¿½ï¿½
@1ï¿½ï¿½':ÆŠï¿½ï¿½ï¿½ï¿½/ï¿½ï¿½bB:
```

(Lots of upside down question marks and one-half signs.)

### Expected results

I see the following message:

```
403 Forbidden

nginx/1.6.2
```

(or, preferably, a custom message like "This Sandstorm app seems to be serving a 404 at the top path (`/`). Read $URL to learn more.")

### Proposed solution

In our nginx configuration in vagrant-spk, always set

`gzip off;`

in `nginx.conf`

I tested that this makes the `403 Forbidden` text appear.

**Comment by paulproteus** [comment]
@zarvox if you can +1 +0 -0 -1 this, I'd be happy to hear that.

@jparyani your sanity-check here might be useful too.

**Comment by jparyani** [comment]
It's a bit sad to disable gzip everywhere. Is there a way to turn gzip for only error codes (4xx and 5xx)?

It's worth noting, I would consider this a bug that should probably be fixed in sandstorm-http-bridge. I'm +0 on disabling gzip for now, and then re-enabling it once someone fixes it (see https://github.com/sandstorm-io/sandstorm/issues/289).

**Comment by paulproteus** [comment]
I vaguely feel like the gzipping should be done by `WebSession` in the Sandstorm platform -- think gzip termination, like gzip termination.

On one hand, apps may want to have opinions about if to gzip a response. On the other hand, I'd be happy enough disabling this in apps and deciding Sandstorm Knows Best.

Thank you for the comment @jparyani ; I can see what you mean that `WebSession` could be fixed instead. I might `gzip off;` for now but will think about fixing `WebSession` instead.

**Comment by zarvox** [comment]
I am +1 on disabling gzip in the nginx conf for now to unbreak things, with the understanding that we really ought to fix WebSession to provide the original content of the HTTP response, because the app may rely on that content to present useful context about the failure to the user.

**Comment by kentonv** [comment]
Keep in mind that there's two ways gzip is used: as a transfer encoding (where it is applied on-demand) and as a content encoding (where the resource is actually persisted gzipped and served up directly).

Due to historical bugs in browsers, both are represented in practice using `Content-Encoding` rather than `Transfer-Encoding`.

If we disable gzip encoding in nginx, I hope that this does not cause it to unzip already-gzipped content. Assuming not, then this seems fine: our own front-end can add gzip, it shouldn't be the app's responsibility.

It is still a bug in sandstorm-http-bridge that error HTML is allowed to be compressed, though.

**Comment by paulproteus** [comment]
This seems to have struck @nicosomb this evening.

**Comment by paulproteus** [comment]
For @kentonv - This will not cause nginx to actively `gunzip` things - apparently `gunzip on;` does that, so I think that covers your concerns.
